<?php
/**
 * @file
 * Install, update and uninstall functions for the spark install profile.
 */

/**
 * Implements hook_install().
 *
 * Perform actions to set up the site for this profile.
 *
 * @see system_install()
 */
function wesnoth_hu_install() {
  /* Since 8.5 there is no minimal.install
  include_once DRUPAL_ROOT . '/core/profiles/minimal/minimal.install';
  minimal_install();
  */

  // Can add code in here to make nodes, terms, etc.
}
