= Specifikáció a Magyar Wesnoth Közösségi Portál Drupal 8 migrációjához
:toc:

A Magyar Wesnoth Közösségi Portál (továbbiakban portál) jelenleg Drupal 6 (továbbiakban D6) alatt fut. A D6 támogatásnak https://www.drupal.org/drupal-6-eol[2016. február 24-től vége], ezért a portált Drupal 8-ra (továbbiakban D8) kell migrálni. Ez a specifikáció összegyűjti a migráláshoz szükséges feladatokat és követelményeket.

== Fejlesztés menete

A fejlesztés a közösség Github tárolóján zajlik. A projekttel kapcsolatos tároló a https://github.com/wesnoth-hu/drupal8[wesnoth-hu/drupal8]. Itt található ennek a specifikációnak és a projekttervnek a forrásfájlja.

Az átállással kapcsolatos megbeszélések a portál fórumán zajlanak. Több téma is létre lett hozva az észrevételekkel, mindenképpen használjuk http://wesnoth.fsf.hu/forums/portal/eszrevetelek[„A portál / Észrevételek” kategóriát]. A specifikáció segít összegyűjteni a különböző témákban felmerült igényeket.

== Projektterv

=== Ütemezés

=== Feladatok állapota

== Grafikai követelmények

- Ne legyen sötét alapon világos betűs, fárasztóbb a szemnek. +
Javasolta: http://wesnoth.fsf.hu/forum/tema/1722#comment-17759[Udi]
- Legyen reszponzív, alkalmazkodjon a képernyő méretéhez (Bootstrap 3-ban gondolkodok, azt ismerem). +
Javasolta: http://wesnoth.fsf.hu/forum/tema/1722#comment-17759[Udi]
- A navigációs elemek egy helyen legyenek, ne legyen a „Saját menü” a bal oldalon, az is a fejlécben kapjon helyet. +
Javasolta: http://wesnoth.fsf.hu/forum/tema/1722#comment-17759[Udi]
- A főoldalon a tartalom több oszlopos legyen, lehessen pl. az újévi képet, bajnoki gratulációt és a szavazást egymás mellé elhelyezni, hogy mindegyik a hajtás fölött látszódjon. +
Javasolta: http://wesnoth.fsf.hu/forum/tema/1722#comment-17759[Udi]
- A hozzászólások megjelenítése egységes legyen, a privát üzeneteknél jelenleg a bal oldalon van a profilkép. +
Javasolta: http://wesnoth.fsf.hu/forum/tema/1722#comment-17759[Udi]
- Használja az 1.13-as verzió logóját és egységeit. +
Javasolta: http://wesnoth.fsf.hu/forum/tema/2342[SilverMage]
- Ha a háttér változna sötétebb színre pl. barna, akkor a LINKEK színe módosulhatna figyelemfelhívóbbra pl. nem látogatott linkl narancs, a látogatott sárgásbarna, de az eddigi is jó, csak legyen megkülönböztetve, hogy látogatott-e vagy sem +
Javasolta: http://wesnoth.fsf.hu/forum/tema/1722#comment-17763[Jf. Tasz]

== Portál követelmények

=== Szövegszerkesztő

- A böngésző helyesírásellenörző funkciója megmaradjon a WYSIWYG mezőben is. +
Javasolta: http://wesnoth.fsf.hu/forum/tema/1722#comment-17759[Jf. Tasz]
- A legalaktartóbb legyen (WYSIWYG), de elérhető legyen a HTML kód rész is. +
Javasolta: http://wesnoth.fsf.hu/forum/tema/1722#comment-17763[Jf. Tasz]
- Mosolygó arcocskák behúzhatóak legyenek, és úgy jelenjenek meg. +
Javasolta: http://wesnoth.fsf.hu/forum/tema/1722#commen+t-17763[Jf. Tasz]
- Mosolygó arcocskákból van-e Wesnoth témájú? Esetleg emeljünk-e át kisméretű képeket a játékból (32x32 pixel, Battle for Wesnoth 1.13.2\images\icons\)? +
Javasolta: http://wesnoth.fsf.hu/forum/tema/1722#comment-17763[Jf. Tasz]
- Állítható betűméret +
Javasolta: http://wesnoth.fsf.hu/forum/tema/1722#comment-17763[Jf. Tasz]
- Spoiler (kiszivárogtatás) funkció, ez a szövegrész alapesetben rejtve van, és klikkre kinyílik (rejtett szöveg megjelenítése) +
Javasolta: http://wesnoth.fsf.hu/forum/tema/1722#comment-17763[Jf. Tasz]
- A tudástár cikkei legyenek átemelve egy wiki jellegű rendszerbe. +
Javasolta: http://wesnoth.fsf.hu/node/2344#comment-17755[Jf. Tasz]

=== Hírek

- A véletlenszerű képek csoportonkénti véletlenszerűsítése. Bármely hírcsoportokhoz (címkékhez) pl. bajnokság: akkor a  glória és a lovag képek tartoznak; a kiadási hírekhez Wesnoth logók; az általános hírhez a paraszt és az erdész egységek, stb. +
Javasolta: http://wesnoth.fsf.hu/forum/tema/1722#comment-17763[Jf. Tasz]

=== Fórum

==== Általános

- Új fórumtéma gomb legyen az adott fórumon belül is. +
Javasolta: http://wesnoth.fsf.hu/forum/tema/1825#comment-14851[Montezuma]
- Megmaradjon a jelölés arra, hogy  bejelentkezettek csak a legutóbbi kilépés óta mik az új bejegyzések (pirossal az ikon) +
Javasolta: http://wesnoth.fsf.hu/forum/tema/1722#comment-17763[Jf. Tasz]
- Megmaradjon a Friss tartalom nyomkövetés (http://wesnoth.fsf.hu/tracker) +
Javasolta: http://wesnoth.fsf.hu/forum/tema/1722#comment-17763[Jf. Tasz]
- Válasznál látszódjon az utóbbi "x" pl.15 bejegyzés, (ne csak az első, mint most). Szöveg kijelölésre, majd klikk egy idézés gombra és megjelenik idézve, utána automatikus új üres alapértlemezett sort szúrjon be. +
Javasolta: http://wesnoth.fsf.hu/forum/tema/1722#comment-17760[negusnyul], http://wesnoth.fsf.hu/forum/tema/1722#comment-17763[Jf. Tasz]
- Olvasottság mérése ne egy érték legyen, pl. 25 hozzászólás után olvasott, hanem pl. az elmúlt 2 héten belül, több mint 20 hozzászólás volt, a mozgó ikonja jó. +
Javasolta: http://wesnoth.fsf.hu/forum/tema/1722#comment-17763[Jf. Tasz]
- Legyen kiemelt fórumtéma (még régebben volt kb. 2010/2011), amit az adminok állítanak, egy kis felkiáltójel kapjon az ikon valamelyik felső sarkába. +
Javasolta: http://wesnoth.fsf.hu/forum/tema/1722#comment-17763[Jf. Tasz]

==== Rangok

- Nagy aktivitásmérő: egy határ kell pl. 1 év, aki ezen belül bejelentkezik az aktívnak számít, aki nem, az inaktív. +
Javasolta: http://wesnoth.fsf.hu/forum/tema/1722#comment-17763[Jf. Tasz]
- Az aktív felhasználókat tovább lehessen rangsorolni: maradhat az eddigi (címkés) csoportrang (bajnok, admin, szerkesztő, bajnokság szervező), de ezeknek az elérését szabályzatba kell foglalni, feltételekhez kötni, újraértékelni és új címeket kiírni (pl.: szerverfüggő, azaz mindig játékra kész; alapító, kiemelt tag, stb.) +
Javasolta: http://wesnoth.fsf.hu/forum/tema/1722#comment-17763[Jf. Tasz]

=== Regisztráció, bejelentkezés

- *FONTOS!* Link ezekre: Adatvédelmi tájékoztató és Felhasználói szabályzat. Ezt meg kéne írni mihamarabb. Legalább egy rövidet kezdetnek. +
Javasolta: http://wesnoth.fsf.hu/forum/tema/1722#comment-17763[Jf. Tasz]
- *FONTOS!* Mit ad ez a közösség?,ezt leírni ezzel növelni az aktív és tettre kész érdeklődő játékosokat +
Javasolta: http://wesnoth.fsf.hu/forum/tema/1722#comment-17763[Jf. Tasz]
- HTTPS bejelentkezés a HTTP helyett. +
Javasolta: http://wesnoth.fsf.hu/forum/tema/1722#comment-17763[Jf. Tasz]
- A nem regisztráltak ne írhasanak az oldalra (arra ott az e-mail) +
Javasolta: http://wesnoth.fsf.hu/forum/tema/1722#comment-17763[Jf. Tasz], http://wesnoth.fsf.hu/forum/tema/1722#comment-17765[Udi]
- Többszörös captcha vagy valami megoldás a robotok és botok ellen; pl: 3+11=szöveges válasz magyarul v. három + 11  = szöveges válasz magyarul v. ehhez hasonló captcha-k kombinálása, tehát pl. 2-3-at kell jól megoldani. +
Javasolta: http://wesnoth.fsf.hu/forum/tema/1722#comment-17763[Jf. Tasz]
- Megerősítő e-mail, amiben van egy link, hogy azzal aktiválja a profilját , a profil aktiválására pl. 48 óra áll rendelkezésre. +
Javasolta: http://wesnoth.fsf.hu/forum/tema/1722#comment-17763[Jf. Tasz]
- A http://wesnoth.fsf.hu/user/register[regisztrációs oldal] szépen legyen megszerkesztve (jelenleg a minimum szabályzat összefolyik). +
Javasolta: http://wesnoth.fsf.hu/forum/tema/1722#comment-17763[Jf. Tasz]
- Több időparaméter függvényében (1 éve, 6 hónapja, 1 hónapja, 2 hete) ennyi tag vált inaktívvá/aktívvá, ennyi új tag lett/ennyi törölte profilját. +
Javasolta: http://wesnoth.fsf.hu/forum/tema/1722#comment-17763[Jf. Tasz]

=== Profil

- Több közösségi link megadásának lehetőségei a kapcsolat résznél pl: Facebook, Twitter, Google+, Skype, nemzetközi wesnoth fórum, és minden egyes opcióhoz bejelölni lehessen, hogy publikus (nem regisztrált is láthatja) v. csak regisztráltaknak v. privát (a felhasználó és adminok láthatják) +
Javasolta: http://wesnoth.fsf.hu/forum/tema/1722#comment-17763[Jf. Tasz]
- Wesnoth modul a profilhoz: legördülő menükből: kedvenc egység, faj, frakció (nem ugyanaz a fajjal), hadjárat - ebből is lehetne felhasználói statot készíteni +
Javasolta: http://wesnoth.fsf.hu/forum/tema/1722#comment-17763[Jf. Tasz]
- Wesnoth Ladder profil és pontok a profilban. +
Javasolta: http://wesnoth.fsf.hu/forum/tema/1722#comment-17765[Udi]
- Aktivitásmérő, ha valaki be van jelentkezve a játék szerverére. +
Javasolta: http://wesnoth.fsf.hu/forum/tema/1722#comment-17761[NymmeL]
- Egy esemény naptár, ahol mindenki be tudja jelölni mikor tud fent lenni szerveren játszani. Ugyanilyen naptárba egy-két elszánt ember beírná a nevét mint bíró vagy tervező vagy ami akar lenni. (Persze ez kedv függő) Így nyomon követhető lenne az események ideje, a felelős személy neve (tudjuk kit kell kérdezgetni stb) és hogy ki jelentkezett már. +
Javasolta: http://wesnoth.fsf.hu/forum/tema/1722#comment-17761[NymmeL], http://wesnoth.fsf.hu/forum/tema/1722#comment-17775[NymmeL]
- A sok helyről ismerhető achievmentek, badgek vagy mérfőldkövek amikkel pontokat lehetne elérni. Lehetnének már meglévők is mint pl: a bajnokságon volt a legtöbb szintlépés stb.  Ennek a megvalósítását a játékosokra lehetne bízni csak a felületet kéne megadni esetleg egy menüpontot hozzá. Olyan lenne mint egy Wikipédia vagy mint egy Fórum. A játékosok megadnák az adott Mod nevét, ezt egy kis listában jelezné egy "linkkel". Mikor rányom kiad még egy listát ahova a játékosok beírták eredményeiket, ha kell fényképes bizonyítékkal. Ezek 2-3 havonta nullázódnának és az a hónapi első helyezett neve bekerülne egy emléktárba. +
Javasolta: http://wesnoth.fsf.hu/forum/tema/1722#comment-17792[NymmeL]

=== Versenyszervezés

- Google jelentkezési kérdőíves integráció, akár a drupal rendszerén belül? +
Javasolta: http://wesnoth.fsf.hu/forum/tema/1722#comment-17763[Jf. Tasz]
- Felfrissíteni a mindenkori használt térképcsomag pálya neveit, úgy, hogy elsődlegesen a magyar elnevezés legyen a döntő pl.: Sulla romjai (Sula Ruins), ha csak angol név van, akkor az angol név marad. +
Javasolta: http://wesnoth.fsf.hu/forum/tema/1722#comment-17763[Jf. Tasz]
- A meccsek feltöltésnél részletesebb szárazadat (vagy automatikusan vagy szövegdobozokban), pl: hány körig tartott, szemben álló hősök, fajok, mindkét ellenfélre (szemben álló oszlopos elrendezés), véletlengenerátor statisztikája, az is jelölve legyen, hogy véletlenszerűen volt kisorsolva az adott faj-vezér vagy meghatározott volt jelentkezésnél, használt módosítók, halál, aranygyűjtés - és ebből egy-egy tornára, bajnokságra azonnal lehet végső statisztikát csinálni és a tippjáték eldöntésében is segít. +
Javasolta: http://wesnoth.fsf.hu/forum/tema/1722#comment-17763[Jf. Tasz], http://wesnoth.fsf.hu/forum/tema/1722#comment-17765[Udi]

=== Dokumentumok

- *FONTOS!* Adatvédelmi tájékoztató és Felhasználói szabályzat. Ezt meg kéne írni mihamarabb. Legalább egy rövidet kezdetnek. +
Javasolta: http://wesnoth.fsf.hu/forum/tema/1722#comment-17763[Jf. Tasz]
- *FONTOS!* Mit ad ez a közösség?,ezt leírni ezzel növelni az aktív és tettre kész érdeklődő játékosokat +
Javasolta: http://wesnoth.fsf.hu/forum/tema/1722#comment-17763[Jf. Tasz]
- „A szabályok Értünk vannak és amiatt, hogy a Közösség működését ne a káosz uralja.” +
Javasolta: http://wesnoth.fsf.hu/forum/tema/1722#comment-17763[Jf. Tasz]
- MWK történelme 2005-től napjainkig (alapítók, lépések, mérföldkövek, nevek, időpontok, új lelkes tagok, szervezők, statisztikák, interjúk, stb.) +
Javasolta: http://wesnoth.fsf.hu/forum/tema/1722#comment-17763[Jf. Tasz]
- Éves összefoglalók, első lenne az idei (2016) és a 0. a tavalyi (2015) +
Javasolta: http://wesnoth.fsf.hu/forum/tema/1722#comment-17763[Jf. Tasz]

== Oldalmegtekintések

=== Új látogatók aránya ===

pass:[2015.] január 13. és 2016. január 13. között az új látogatók aránya 31,3%, a visszatérőké 68,9%.

=== Leglátogatottabb oldalak ===

A következő táblázat a 2015. január 13. és 2016. január 13. közötti leggyakrabban látogatott oldalakat tartalmazza.

[format="csv", options="header"]
|===
Oldal,Egyedi oldalmegtekintések,Oldalon töltött átl. idő
/,14385,00:02:21
/jatek/letoltes,1782,00:02:08
/tracker,1095,00:00:40
/messages,1444,00:00:18
/bajnoksag/allas,1003,00:02:24
/forum/tema/1445,1427,00:04:38
/forum,746,00:00:27
/kieg,719,00:01:52
/node,805,00:00:51
/bajnoksag/merkozesek,492,00:01:28
/comment/reply/1877,482,00:02:41
/comment/reply/1382,463,00:01:15
/tudastar,444,00:00:19
/jatek,381,00:00:21
/bajnoksag2015jelentkezok,344,00:01:34
/messages/view/3759,251,00:02:43
/bajnoksag,273,00:00:33
/jatek/kezikonyv,382,00:02:52
/node/393,361,00:02:50
/users/krogen,255,00:00:07
/forums/harc-wesnoth-ert/szabad-beszelgetes,230,00:00:30
/mwb2015szabaly,256,00:04:02
/users/miroku,94,00:00:17
/jatek/palyak,260,00:00:30
/admin/wesnoth/verseny/merkozesek,28,00:00:16
|===

=== Leggyakrabb felbontások ===

A következő táblázat a 2015. január 13. és 2016. január 13. közötti leggyakrabb felbontásokat tartalmazza.

[format="csv", options="header"]
|===
Képernyőfelbontás,Munkamenetek,Munkamenetek %-os aránya
1366x768,5963,"30,82%"
1280x1024,2668,"13,79%"
1920x1080,1308,"6,76%"
1680x1050,1246,"6,44%"
1024x768,1153,"5,96%"
(not set),822,"4,25%"
1280x800,743,"3,84%"
1600x900,720,"3,72%"
320x534,528,"2,73%"
1440x900,520,"2,69%"
|===

=== Leggyakrabb böngészők ===

A következő táblázat a 2015. január 13. és 2016. január 13. közötti leggyakrabb operációs rendszereket tartalmazza.

[format="csv", options="header"]
|===
Böngésző,Munkamenetek,Munkamenetek %-os aránya
Chrome,9345,"48,30%"
Firefox,7167,"37,04%"
Android Browser,872,"4,51%"
Safari,669,"3,46%"
Internet Explorer,638,"3,30%"
Opera,397,"2,05%"
(not set),119,"0,62%"
Opera Mini,61,"0,32%"
Edge,19,"0,10%"
Maxthon,18,"0,09%"
|===

=== Leggyakrabb operációs rendszerek ===

A következő táblázat a 2015. január 13. és 2016. január 13. közötti leggyakrabb operációs rendszereket tartalmazza.
[format="csv", options="header"]
|===
Operációs rendszer,Munkamenetek,Munkamenetek %-os aránya
Windows,13993,"72,32%"
Android,2331,"12,05%"
Linux,1465,"7,57%"
Macintosh,722,"3,73%"
iOS,451,"2,33%"
Windows Phone,236,"1,22%"
(not set),141,"0,73%"
Firefox OS,2,"0,01%"
Nintendo Wii,2,"0,01%"
Samsung,2,"0,01%"
|===
